name: Run tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
      - name: Test with pytest
        run: pytest --cov=./hdx_redis_lib
        env:
          REDIS_STREAM_HOST: localhost
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        if: matrix.python-version == '3.10'
